#!/usr/bin/env python3
"""
Build helper for Wine/Rosetta environments where ninja can't spawn subprocesses.
Reads the compile database from ninja and executes commands sequentially.
Then runs the link commands via ninja -t commands.
"""
import json
import subprocess
import sys
import os

def main():
    build_dir = sys.argv[1] if len(sys.argv) > 1 else "Z:\\project\\build"

    # Read compile database generated by: ninja -t compdb
    compdb_path = "C:\\compdb.json"
    # On Linux filesystem
    compdb_linux = "/home/wine/.wine/drive_c/compdb.json"

    if not os.path.exists(compdb_linux):
        print("ERROR: compdb.json not found. Run ninja -t compdb first.", file=sys.stderr)
        sys.exit(1)

    with open(compdb_linux) as f:
        commands = json.load(f)

    # Filter out empty commands
    compile_cmds = [c for c in commands if c.get("command", "").strip()]

    total = len(compile_cmds)
    print(f"Building {total} targets...")

    failed = 0
    for i, entry in enumerate(compile_cmds):
        cmd = entry["command"]
        directory = entry.get("directory", build_dir)
        output = entry.get("output", "?")

        print(f"[{i+1}/{total}] {output}")

        # Create a batch file for this command
        bat_content = f"@echo off\ncall C:\\x64.bat\ncd /d {directory}\n{cmd}\n"
        bat_path = "/home/wine/.wine/drive_c/compile_cmd.bat"
        with open(bat_path, "w") as bf:
            bf.write(bat_content)

        result = subprocess.run(
            ["wine64", "cmd", "/c", "C:\\compile_cmd.bat"],
            capture_output=True, text=True, timeout=120
        )

        if result.returncode != 0:
            print(f"  FAILED (exit {result.returncode})")
            if result.stderr:
                print(result.stderr[:500])
            if result.stdout:
                print(result.stdout[:500])
            failed += 1
            if failed > 5:
                print("Too many failures, stopping.")
                sys.exit(1)

    print(f"\nCompilation: {total - failed}/{total} succeeded, {failed} failed")

    if failed > 0:
        sys.exit(1)

    # Now run the link steps via batch files
    # First, create the static library
    print("\nLinking libcef_dll_wrapper.lib...")
    link_bat = "/home/wine/.wine/drive_c/link_cmd.bat"

    # Get all wrapper obj files
    wrapper_objs = [c["output"] for c in compile_cmds if "libcef_dll_wrapper" in c.get("output", "")]
    obj_list = " ".join(wrapper_objs)

    with open(link_bat, "w") as bf:
        bf.write(f"@echo off\ncall C:\\x64.bat\ncd /d {build_dir}\n")
        bf.write(f"lib.exe /nologo /OUT:libcef_dll_wrapper.lib {obj_list}\n")

    result = subprocess.run(["wine64", "cmd", "/c", "C:\\link_cmd.bat"], capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        print(f"lib.exe failed: {result.stderr} {result.stdout}")
    else:
        print("  OK")

    # Link subprocess exe
    sub_objs = [c["output"] for c in compile_cmds if "nexus_js_subprocess" in c.get("output", "")]
    if sub_objs:
        print("\nLinking nexus_js_subprocess.exe...")
        obj_list = " ".join(sub_objs)
        with open(link_bat, "w") as bf:
            bf.write(f"@echo off\ncall C:\\x64.bat\ncd /d {build_dir}\n")
            bf.write(f"link.exe /nologo /SUBSYSTEM:WINDOWS /OUT:nexus_js_subprocess.exe {obj_list} libcef_dll_wrapper.lib Z:\\project\\third_party\\cef\\cef_dist\\Release\\libcef.lib\n")

        result = subprocess.run(["wine64", "cmd", "/c", "C:\\link_cmd.bat"], capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print(f"link.exe failed: {result.stderr} {result.stdout}")
        else:
            print("  OK")

    # Link main DLL
    dll_objs = [c["output"] for c in compile_cmds if "nexus_js_loader" in c.get("output", "")]
    if dll_objs:
        print("\nLinking nexus_js_loader.dll...")
        obj_list = " ".join(dll_objs)
        with open(link_bat, "w") as bf:
            bf.write(f"@echo off\ncall C:\\x64.bat\ncd /d {build_dir}\n")
            bf.write(f"link.exe /nologo /DLL /OUT:nexus_js_loader.dll {obj_list} libcef_dll_wrapper.lib Z:\\project\\third_party\\cef\\cef_dist\\Release\\libcef.lib d3d11.lib dxgi.lib\n")

        result = subprocess.run(["wine64", "cmd", "/c", "C:\\link_cmd.bat"], capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print(f"link.exe failed: {result.stderr} {result.stdout}")
        else:
            print("  OK")

    print("\nDone!")

if __name__ == "__main__":
    main()
